name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      web:
        image: python:3.9
        ports:
          - 5000:5000
        options: >-
          --health-cmd "curl --fail http://localhost:5000 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest requests safety

      - name: Dependency Security Check
        run: safety check || true

      - name: Start Flask App
        run: |
          nohup python app.py > flask.log 2>&1 &
          sleep 5

      - name: UI Test Over HTTP
        run: |
          python -c "
import requests
res = requests.post('http://localhost:5000', data={'term': '<script>alert(1)</script>'})
assert res.status_code == 200
assert 'script' not in res.text
"
