name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install safety requests

      - name: Dependency Security Check
        run: safety check || true

      - name: Start Flask App
        run: |
          nohup python app.py > flask.log 2>&1 &
          sleep 5

      - name: UI Test Over HTTP
        run: |
          python -c "import requests; \
r = requests.post('http://localhost:5000', data={'term': '<script>alert(1)</script>'}); \
assert r.status_code == 200; \
assert '<script>' not in r.text"
