name: CI Pipeline with ESLint Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install safety

      - name: Install Node.js dependencies
        run: npm install

      - name: Run Dependency Security Check
        run: safety check || true

      - name: Start Flask App
        run: |
          nohup python app.py > flask.log 2>&1 &
          sleep 5

      - name: UI Test Over HTTP
        run: >
          python -c "import requests; res = requests.post('http://localhost:5000', data={'term': '<script>alert(1)</script>'}); assert res.status_code == 200; assert '<script>' not in res.text"

      - name: Run ESLint with SARIF Output
        run: |
          mkdir -p reports
          npm run lint

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: reports/eslint-results.sarif
